package com.javaclaw.server.persistence;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/** V003 在写入成功版本前逐表检查关键列；可重入 DDL 不能掩盖部分安装。 */
final class CodingSchemaValidation {
    void validate(Connection connection) throws SQLException {
        for (String query : List.of(
                "SELECT ID,WORKSPACE_ID,TURN_ID,EXECUTION_ROOT,CODE,EVIDENCE_JSON,CREATED_AT FROM CORE.WORKSPACE_SECURITY_EVENT WHERE 1 = 0",
                "SELECT SNAPSHOT_ID, WORKSPACE_ID, SELECTION_JSON, SELECTION_DIGEST, CREATED_AT FROM CORE.CODING_EXECUTION_ENVIRONMENT WHERE 1 = 0",
                "SELECT WORKSPACE_ID, REVISION, SPEC_JSON, UPDATED_AT FROM CORE.CODING_ENVIRONMENT WHERE 1 = 0",
                "SELECT TURN_ID, ENVIRONMENT_JSON, ENVIRONMENT_DIGEST, SELECTION_JSON, SELECTION_DIGEST, CREATED_AT FROM CORE.TURN_CODING_ENVIRONMENT WHERE 1 = 0",
                "SELECT ID, TURN_ID, WORKSPACE_ID, CALL_ID, OPERATION_NAME, REQUEST_DIGEST, EXECUTION_ROOT, STATE, REQUEST_JSON, PREPARATION_JSON, DEPENDENCY_EVIDENCE_JSON, RESULT_JSON, OUTPUT_JSON, SUCCESS, FACTS_JSON FROM CORE.CODING_OPERATION WHERE 1 = 0",
                "SELECT ID, OPERATION_ID, TURN_ID, WORKSPACE_ID, STATE, COMMAND_JSON, EXIT_CODE, OUTPUT_BYTES, INPUT_SEQUENCE, INPUT_DIGEST, INPUT_STATE, FINAL_FACT_RECORDED FROM CORE.CODING_TERMINAL WHERE 1 = 0",
                "SELECT SESSION_ID, OFFSET_BYTES, CONTENT_DIGEST, CONTENT_LENGTH FROM CORE.CODING_TERMINAL_OUTPUT WHERE 1 = 0",
                "SELECT ARTIFACT_DIGEST, TOOLCHAIN_KIND, WORKSPACE_ID, ARTIFACT_JSON, INSTALLATION_ID, JOB_ID, STATE, ERROR_CODE FROM CORE.CODING_TOOLCHAIN WHERE 1 = 0",
                "SELECT ID, TURN_ID, OPERATION_ID, GRANT_JSON, STATE, TRANSFERRED_BYTES FROM CORE.CODING_NETWORK_GRANT WHERE 1 = 0")) {
            try (var statement = connection.createStatement();
                    var ignored = statement.executeQuery(query)) {
                // 缺表或缺列立即失败，SCHEMA_HISTORY 不记录成功。
            }
        }
    }
}
