CREATE TABLE CORE.EXTENSION (
    ID VARCHAR(240) PRIMARY KEY,
    TRUST_LEVEL VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE_REVISION BIGINT DEFAULT 1 NOT NULL CHECK (STATE_REVISION > 0),
    DESCRIPTOR CLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.EXTENSION_TRUST_KEY (
    KEY_ID VARCHAR(80) PRIMARY KEY,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    FINGERPRINT CHAR(64) NOT NULL UNIQUE,
    ATTACHMENT_DIGEST CHAR(64) NOT NULL REFERENCES CORE.ATTACHMENT (DIGEST),
    PUBLIC_KEY VARBINARY(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.THIRD_PARTY_BUNDLE (
    EXTENSION_ID VARCHAR(240) PRIMARY KEY REFERENCES CORE.EXTENSION (ID) ON DELETE CASCADE,
    MANIFEST_DIGEST CHAR(64) NOT NULL UNIQUE,
    SIGNING_KEY_ID VARCHAR(80) NOT NULL REFERENCES CORE.EXTENSION_TRUST_KEY (KEY_ID),
    INSTALL_DIRECTORY VARCHAR(160) NOT NULL UNIQUE,
    PERMISSION_REVIEW CLOB NOT NULL,
    FAILURE_COUNT INT NOT NULL DEFAULT 0 CHECK (FAILURE_COUNT >= 0),
    HEALTH_STATE VARCHAR(32) NOT NULL DEFAULT 'NOT_PROBED',
    LAST_HEALTH_AT TIMESTAMP WITH TIME ZONE,
    NEXT_RETRY_AT TIMESTAMP WITH TIME ZONE,
    LAST_FAILURE VARCHAR(1000),
    PENDING_TRASH_NAME VARCHAR(160)
);
CREATE TABLE CORE.THIRD_PARTY_REMOVAL (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    DESCRIPTOR CLOB NOT NULL,
    MANIFEST_DIGEST CHAR(64) NOT NULL,
    SIGNING_KEY_ID VARCHAR(80) NOT NULL REFERENCES CORE.EXTENSION_TRUST_KEY (KEY_ID),
    PERMISSION_REVIEW CLOB NOT NULL,
    TRASH_NAME VARCHAR(160) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REMOVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    RESTORED_REVISION BIGINT,
    PURGED_AT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (EXTENSION_ID, REVISION)
);
CREATE UNIQUE INDEX CORE.THIRD_PARTY_REMOVAL_BY_TRASH ON CORE.THIRD_PARTY_REMOVAL (TRASH_NAME);
CREATE TABLE CORE.EXTENSION_SCHEMA (
    EXTENSION_ID VARCHAR(240) PRIMARY KEY,
    SCHEMA_NAME VARCHAR(80) NOT NULL UNIQUE
);
CREATE TABLE CORE.THIRD_PARTY_DOCUMENT (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    COLLECTION_NAME VARCHAR(240) NOT NULL,
    DOCUMENT_KEY VARCHAR(500) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (EXTENSION_ID, COLLECTION_NAME, DOCUMENT_KEY)
);
CREATE TABLE CORE.THIRD_PARTY_BLOB (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    DIGEST CHAR(64) NOT NULL,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    BLOB_PATH VARCHAR(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (EXTENSION_ID, DIGEST)
);
CREATE TABLE CORE.LIFECYCLE_LEASE (
    ID CHAR(36) PRIMARY KEY,
    OWNER VARCHAR(240) NOT NULL,
    KIND VARCHAR(80) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.VAULT_KEY_STATE (
    SINGLETON BOOLEAN PRIMARY KEY CHECK (SINGLETON = TRUE),
    ACTIVE_KEY_ID VARCHAR(120) NOT NULL,
    PREVIOUS_KEY_ID VARCHAR(120),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (PREVIOUS_KEY_ID IS NULL OR PREVIOUS_KEY_ID <> ACTIVE_KEY_ID)
);
CREATE TABLE CORE.CREDENTIAL_SECRET (
    NAMESPACE VARCHAR(240) NOT NULL,
    SECRET_ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    FORMAT_VERSION INT NOT NULL CHECK (FORMAT_VERSION > 0),
    NONCE VARBINARY(12) NOT NULL,
    CIPHERTEXT BLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (NAMESPACE, SECRET_ID),
    CHECK (OCTET_LENGTH(NONCE) = 12),
    CHECK (OCTET_LENGTH(CIPHERTEXT) >= 16)
);
CREATE TABLE CORE.INPUT_REQUEST (
    ID VARCHAR(240) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    PRODUCER_ID VARCHAR(240) NOT NULL,
    PROMPT VARCHAR(1000) NOT NULL,
    RESPONSE_SCHEMA CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    RESPONSE_PAYLOAD CLOB,
    RESOLUTION_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (EXPIRES_AT > CREATED_AT),
    CHECK ((STATE = 'RESOLVED') = (RESPONSE_PAYLOAD IS NOT NULL)),
    CHECK ((STATE IN ('EXPIRED', 'CANCELLED')) = (RESOLUTION_REASON IS NOT NULL))
);
CREATE INDEX CORE.INPUT_REQUEST_BY_TURN ON CORE.INPUT_REQUEST (TURN_ID, CREATED_AT, ID);
CREATE INDEX CORE.INPUT_REQUEST_BY_STATE ON CORE.INPUT_REQUEST (STATE, EXPIRES_AT);
CREATE TABLE CORE.EXTENSION_JOB (
    ID VARCHAR(240) PRIMARY KEY,
    EXTENSION_ID VARCHAR(240) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    JOB_TYPE VARCHAR(240) NOT NULL,
    DEFINITION_ID VARCHAR(240) NOT NULL,
    DEFINITION_REVISION BIGINT NOT NULL CHECK (DEFINITION_REVISION > 0),
    FROZEN_INPUT CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    CHECKPOINT CLOB NOT NULL,
    NEXT_UNIT_SEQUENCE BIGINT NOT NULL CHECK (NEXT_UNIT_SEQUENCE > 0),
    ACTIVE_UNIT_SEQUENCE BIGINT,
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (ACTIVE_UNIT_SEQUENCE IS NULL OR (ACTIVE_UNIT_SEQUENCE > 0 AND ACTIVE_UNIT_SEQUENCE < NEXT_UNIT_SEQUENCE)),
    CHECK ((STATE = 'FAILED') = (ERROR_CODE IS NOT NULL)),
    CHECK (ACTIVE_UNIT_SEQUENCE IS NULL OR STATE = 'RUNNING')
);
CREATE INDEX CORE.EXTENSION_JOB_BY_WORKSPACE ON CORE.EXTENSION_JOB (WORKSPACE_ID, UPDATED_AT DESC, ID);
CREATE INDEX CORE.EXTENSION_JOB_RUNNABLE ON CORE.EXTENSION_JOB (STATE, UPDATED_AT, ID);
CREATE TABLE CORE.EXTENSION_JOB_UNIT (
    JOB_ID VARCHAR(240) NOT NULL REFERENCES CORE.EXTENSION_JOB (ID) ON DELETE CASCADE,
    UNIT_SEQUENCE BIGINT NOT NULL CHECK (UNIT_SEQUENCE > 0),
    UNIT_ID VARCHAR(240) NOT NULL,
    INTENT CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RESULT_PAYLOAD CLOB,
    CHECKPOINT CLOB,
    TURN_ID CHAR(36) REFERENCES CORE.AGENT_TURN (ID),
    EFFECT_RECEIPT_KEY VARCHAR(500),
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (JOB_ID, UNIT_SEQUENCE),
    UNIQUE (JOB_ID, UNIT_ID),
    CHECK ((STATE = 'INTENT_RECORDED') = (COMPLETED_AT IS NULL)),
    CHECK ((STATE = 'COMPLETED') = (CHECKPOINT IS NOT NULL)),
    CHECK ((STATE = 'FAILED') = (ERROR_CODE IS NOT NULL))
);
CREATE TABLE CORE.EXTENSION_JOB_INPUT_WAIT (
    JOB_ID VARCHAR(240) PRIMARY KEY REFERENCES CORE.EXTENSION_JOB (ID) ON DELETE CASCADE,
    REQUEST_ID VARCHAR(240) NOT NULL UNIQUE REFERENCES CORE.INPUT_REQUEST (ID) ON DELETE CASCADE,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.EXTENSION_JOB_INPUT_WAIT_BY_REQUEST ON CORE.EXTENSION_JOB_INPUT_WAIT (REQUEST_ID);
CREATE TABLE CORE.PRIVATE_NETWORK_GRANT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE INDEX CORE.PRIVATE_NETWORK_GRANT_LATEST ON CORE.PRIVATE_NETWORK_GRANT (WORKSPACE_ID, ID, REVISION DESC);
CREATE TABLE CORE.UNATTENDED_TOOL_GRANT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE INDEX CORE.UNATTENDED_TOOL_GRANT_LATEST ON CORE.UNATTENDED_TOOL_GRANT (WORKSPACE_ID, ID, REVISION DESC);
CREATE TABLE CORE.UNATTENDED_TOOL_USE (
    GRANT_ID VARCHAR(240) NOT NULL,
    INVOCATION_ID VARCHAR(240) NOT NULL,
    GRANT_REVISION BIGINT NOT NULL CHECK (GRANT_REVISION > 0),
    OUTCOME VARCHAR(32) NOT NULL,
    CONSUMED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (GRANT_ID, INVOCATION_ID),
    FOREIGN KEY (GRANT_ID, GRANT_REVISION)
        REFERENCES CORE.UNATTENDED_TOOL_GRANT (ID, REVISION)
);
CREATE INDEX CORE.UNATTENDED_TOOL_USE_BY_GRANT ON CORE.UNATTENDED_TOOL_USE (GRANT_ID, CONSUMED_AT);
CREATE TABLE CORE.PERMISSION_DECISION_TRACE (
    ID VARCHAR(240) PRIMARY KEY,
    DECISION_SEQUENCE BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    GRANT_KIND VARCHAR(32) NOT NULL,
    GRANT_ID VARCHAR(240) NOT NULL,
    ALLOWED BOOLEAN NOT NULL,
    PAYLOAD CLOB NOT NULL,
    DECIDED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.PERMISSION_DECISION_BY_GRANT ON CORE.PERMISSION_DECISION_TRACE (
        WORKSPACE_ID,
        GRANT_KIND,
        GRANT_ID,
        DECIDED_AT DESC,
        DECISION_SEQUENCE DESC
    );
