CREATE TABLE CORE.CHILD_TURN_RESERVATION (
    CHILD_THREAD_ID UUID PRIMARY KEY REFERENCES CORE.AGENT_THREAD(ID),
    PARENT_TURN_ID UUID NOT NULL REFERENCES CORE.AGENT_TURN(ID),
    INPUT_TOKENS BIGINT NOT NULL,
    OUTPUT_TOKENS BIGINT NOT NULL,
    TOOL_CALLS INT NOT NULL,
    WALL_TIME_MILLIS BIGINT NOT NULL,
    CONFIGURATION_JSON CLOB NOT NULL,
    CATALOG_JSON CLOB NOT NULL
);
CREATE INDEX CHILD_TURN_PARENT ON CORE.CHILD_TURN_RESERVATION(PARENT_TURN_ID);
