CREATE TABLE CORE.MCP_ENDPOINT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION >= 0),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE INDEX CORE.MCP_ENDPOINT_LATEST ON CORE.MCP_ENDPOINT (WORKSPACE_ID, ID, REVISION DESC);
CREATE TABLE CORE.MCP_CATALOG_ENTRY (
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION > 0),
    KIND VARCHAR(32) NOT NULL,
    ENTRY_NAME VARCHAR(160) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    PRIMARY KEY (ENDPOINT_ID, CATALOG_REVISION, KIND, ENTRY_NAME)
);
CREATE INDEX CORE.MCP_CATALOG_PAGE ON CORE.MCP_CATALOG_ENTRY (ENDPOINT_ID, CATALOG_REVISION, KIND, ENTRY_NAME);
CREATE TABLE CORE.MCP_CATALOG_REFRESH (
    ENDPOINT_ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    PAGES_COMPLETED INT NOT NULL CHECK (PAGES_COMPLETED BETWEEN 0 AND 50),
    ENTRIES_DISCOVERED INT NOT NULL CHECK (ENTRIES_DISCOVERED BETWEEN 0 AND 10000),
    COMMITTED_CATALOG_REVISION BIGINT CHECK (COMMITTED_CATALOG_REVISION > 0),
    DETAIL VARCHAR(500),
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.MCP_TOOL_INVOCATION (
    IDEMPOTENCY_KEY VARCHAR(500) PRIMARY KEY,
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION > 0),
    TOOL_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RESULT_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.MCP_TOOL_INVOCATION_BY_ENDPOINT ON CORE.MCP_TOOL_INVOCATION (ENDPOINT_ID, UPDATED_AT DESC);
CREATE TABLE CORE.MCP_HEALTH (
    ENDPOINT_ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    CHECKED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.MCP_OAUTH_SESSION (
    ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    AUTHORIZATION_URI VARCHAR(4096) NOT NULL,
    CREDENTIAL_NAMESPACE VARCHAR(240) NOT NULL,
    CREDENTIAL_ID VARCHAR(240) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    DETAIL VARCHAR(500),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.MCP_OAUTH_BY_ENDPOINT ON CORE.MCP_OAUTH_SESSION (ENDPOINT_ID, UPDATED_AT DESC);

