CREATE SCHEMA IF NOT EXISTS CORE;
CREATE TABLE CORE.WORKSPACE (
    ID CHAR(36) PRIMARY KEY,
    NAME VARCHAR(240) NOT NULL,
    ROOT_PATH VARCHAR(4096) NOT NULL UNIQUE,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.WORKSPACE_INSTRUCTION_SETTING (
    WORKSPACE_ID CHAR(36) PRIMARY KEY REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    FALLBACK_BASENAME VARCHAR(120),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.AGENT_THREAD (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PARENT_THREAD_ID CHAR(36) REFERENCES CORE.AGENT_THREAD (ID),
    EXECUTION_INTENT VARCHAR(32) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    NEXT_SEQUENCE BIGINT NOT NULL DEFAULT 1 CHECK (NEXT_SEQUENCE > 0),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.AGENT_TURN (
    ID CHAR(36) PRIMARY KEY,
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    STATUS VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    INPUT_TOKENS BIGINT NOT NULL CHECK (INPUT_TOKENS > 0),
    OUTPUT_TOKENS BIGINT NOT NULL CHECK (OUTPUT_TOKENS > 0),
    TOOL_CALLS INT NOT NULL CHECK (TOOL_CALLS >= 0),
    CHILD_THREADS INT NOT NULL CHECK (CHILD_THREADS BETWEEN 0 AND 4),
    WALL_TIME_MILLIS BIGINT NOT NULL CHECK (WALL_TIME_MILLIS > 0),
    ROLE_ID VARCHAR(240) NOT NULL,
    ROLE_REVISION BIGINT NOT NULL CHECK (ROLE_REVISION > 0),
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL CHECK (PROVIDER_REVISION > 0),
    MODEL VARCHAR(1000) NOT NULL,
    PERMISSION_PROFILE_ID VARCHAR(240) NOT NULL,
    PERMISSION_PROFILE_VERSION BIGINT NOT NULL CHECK (PERMISSION_PROFILE_VERSION > 0),
    EXECUTION_ROOT VARCHAR(4096) NOT NULL,
    PROMPT_MANIFEST_DIGEST CHAR(64) NOT NULL,
    TOOL_CATALOG_DIGEST CHAR(64) NOT NULL,
    RESOLVED_CONFIG_JSON CLOB NOT NULL,
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.TURN_CANCELLATION (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    REASON VARCHAR(500) NOT NULL,
    REQUESTED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.PROMPT_MANIFEST_SNAPSHOT (
    DIGEST CHAR(64) PRIMARY KEY,
    PAYLOAD CLOB NOT NULL
);
CREATE TABLE CORE.TURN_PROMPT_SNAPSHOT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PAYLOAD CLOB NOT NULL,
    DIGEST CHAR(64) NOT NULL
);
CREATE TABLE CORE.TURN_TOOL_CATALOG_SNAPSHOT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PAYLOAD CLOB NOT NULL,
    DIGEST CHAR(64) NOT NULL
);
CREATE TABLE CORE.TURN_UNATTENDED_EXECUTION_SCOPE (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    SCHEDULE_ID VARCHAR(240) NOT NULL,
    SCHEDULE_REVISION BIGINT NOT NULL CHECK (SCHEDULE_REVISION > 0),
    OCCURRENCE_ID VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.TURN_UNATTENDED_SCOPE_BY_OCCURRENCE
    ON CORE.TURN_UNATTENDED_EXECUTION_SCOPE (WORKSPACE_ID, SCHEDULE_ID, SCHEDULE_REVISION, OCCURRENCE_ID);
CREATE TABLE CORE.TURN_EXECUTION_CHECKPOINT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PHASE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    INPUT_TOKENS BIGINT NOT NULL CHECK (INPUT_TOKENS >= 0),
    OUTPUT_TOKENS BIGINT NOT NULL CHECK (OUTPUT_TOKENS >= 0),
    REASONING_TOKENS BIGINT NOT NULL CHECK (REASONING_TOKENS >= 0),
    CACHED_INPUT_TOKENS BIGINT NOT NULL CHECK (CACHED_INPUT_TOKENS >= 0),
    CONSUMED_TOOL_CALLS INT NOT NULL CHECK (CONSUMED_TOOL_CALLS >= 0),
    MODEL_INVOCATIONS INT NOT NULL CHECK (MODEL_INVOCATIONS >= 0),
    TOOL_BATCH CLOB NOT NULL,
    NEXT_TOOL_INDEX INT NOT NULL CHECK (NEXT_TOOL_INDEX >= 0),
    VISIBLE_TOOLS CLOB NOT NULL,
    ACTIVE_INTENT_DIGEST CHAR(64),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((PHASE IN (
        'MODEL_IN_FLIGHT', 'TOOL_WAITING_APPROVAL', 'TOOL_APPROVAL_RESOLVED', 'TOOL_IN_FLIGHT'
    )) = (ACTIVE_INTENT_DIGEST IS NOT NULL))
);
CREATE TABLE CORE.APPROVAL_REQUEST (
    ID VARCHAR(160) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CALL_ID VARCHAR(240) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOOL_NAME VARCHAR(320) NOT NULL,
    TOOL_REVISION BIGINT NOT NULL CHECK (TOOL_REVISION > 0),
    RISK VARCHAR(32) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    EXPLANATION VARCHAR(1000) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    RESOLUTION_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (TURN_ID, CALL_ID)
);
CREATE INDEX CORE.APPROVAL_BY_STATE ON CORE.APPROVAL_REQUEST (STATE, CREATED_AT);
CREATE TABLE CORE.ITEM (
    ID CHAR(36) PRIMARY KEY,
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    SEQUENCE BIGINT NOT NULL CHECK (SEQUENCE > 0),
    KIND VARCHAR(160) NOT NULL,
    SCHEMA_ID VARCHAR(320) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    UNIQUE (THREAD_ID, SEQUENCE)
);
CREATE INDEX CORE.ITEM_BY_TURN ON CORE.ITEM (TURN_ID, SEQUENCE);
CREATE TABLE CORE.EVENT (
    SEQUENCE BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    THREAD_ID CHAR(36),
    TURN_ID CHAR(36),
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOPIC VARCHAR(320) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.OUTBOX (
    ID CHAR(36) PRIMARY KEY,
    DESTINATION VARCHAR(320) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(500) NOT NULL UNIQUE,
    PAYLOAD CLOB NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    ATTEMPTS INT NOT NULL DEFAULT 0 CHECK (ATTEMPTS >= 0),
    NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.COMMAND_RESULT (
    IDEMPOTENCY_KEY VARCHAR(200) PRIMARY KEY,
    METHOD_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    RESPONSE_PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.EFFECT_RECEIPT (
    IDEMPOTENCY_KEY VARCHAR(500) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CALL_ID VARCHAR(240) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOOL_NAME VARCHAR(320) NOT NULL,
    TOOL_REVISION BIGINT NOT NULL CHECK (TOOL_REVISION > 0),
    REQUEST_DIGEST CHAR(64) NOT NULL,
    RESULT_DIGEST CHAR(64) NOT NULL,
    RESULT_PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.ATTACHMENT (
    DIGEST CHAR(64) PRIMARY KEY,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    BLOB_PATH VARCHAR(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.ATTACHMENT_GLOBAL_CLAIM (
    ATTACHMENT_DIGEST CHAR(64) PRIMARY KEY REFERENCES CORE.ATTACHMENT (DIGEST) ON DELETE CASCADE,
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE CORE.ATTACHMENT_WORKSPACE_CLAIM (
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    ATTACHMENT_DIGEST CHAR(64) NOT NULL REFERENCES CORE.ATTACHMENT (DIGEST) ON DELETE CASCADE,
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (WORKSPACE_ID, ATTACHMENT_DIGEST)
);
CREATE TABLE CORE.ATTACHMENT_UPLOAD_QUOTA (
    ID SMALLINT PRIMARY KEY CHECK (ID = 1)
);
INSERT INTO CORE.ATTACHMENT_UPLOAD_QUOTA (ID) VALUES (1);
CREATE TABLE CORE.ATTACHMENT_UPLOAD (
    ID CHAR(36) PRIMARY KEY,
    SCOPE_KIND VARCHAR(24) NOT NULL CHECK (SCOPE_KIND IN ('GLOBAL', 'WORKSPACE')),
    WORKSPACE_ID CHAR(36) REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    STATE VARCHAR(24) NOT NULL CHECK (STATE IN ('ACTIVE', 'COMPLETED', 'ABORTED', 'FAILED', 'EXPIRED')),
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    EXPECTED_DIGEST CHAR(64) NOT NULL,
    EXPECTED_BYTES BIGINT NOT NULL CHECK (EXPECTED_BYTES BETWEEN 1 AND 67108864),
    RECEIVED_BYTES BIGINT NOT NULL CHECK (RECEIVED_BYTES BETWEEN 0 AND EXPECTED_BYTES),
    NEXT_CHUNK_INDEX INTEGER NOT NULL CHECK (NEXT_CHUNK_INDEX BETWEEN 0 AND 1024),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    ATTACHMENT_DIGEST CHAR(64) REFERENCES CORE.ATTACHMENT (DIGEST),
    FAILURE_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((SCOPE_KIND = 'WORKSPACE') = (WORKSPACE_ID IS NOT NULL)),
    CHECK ((STATE = 'COMPLETED') = (ATTACHMENT_DIGEST IS NOT NULL)),
    CHECK ((STATE IN ('ABORTED', 'FAILED', 'EXPIRED')) = (FAILURE_REASON IS NOT NULL))
);
CREATE INDEX CORE.IDX_ATTACHMENT_UPLOAD_ACTIVE ON CORE.ATTACHMENT_UPLOAD (STATE, EXPIRES_AT);
