CREATE TABLE CORE.AGENT_ROLE (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    LIFECYCLE VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE TABLE CORE.PROVIDER (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    LIFECYCLE VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE INDEX CORE.AGENT_ROLE_LATEST ON CORE.AGENT_ROLE (ID, REVISION DESC);
CREATE INDEX CORE.PROVIDER_LATEST ON CORE.PROVIDER (ID, REVISION DESC);
CREATE TABLE CORE.PROVIDER_VERIFICATION (
    IDEMPOTENCY_KEY VARCHAR(200) PRIMARY KEY,
    METHOD_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL CHECK (PROVIDER_REVISION > 0),
    MODEL VARCHAR(1000) NOT NULL,
    PURPOSE VARCHAR(32) NOT NULL CHECK (PURPOSE IN ('CHAT', 'EMBEDDING')),
    STATE VARCHAR(32) NOT NULL
        CHECK (STATE IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED', 'UNKNOWN_OUTCOME')),
    RESULT_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((STATE = 'RUNNING') = (RESULT_PAYLOAD IS NULL)),
    FOREIGN KEY (PROVIDER_ID, PROVIDER_REVISION) REFERENCES CORE.PROVIDER (ID, REVISION)
);
CREATE TABLE CORE.PROMPT_OPTIMIZATION (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    SOURCE_ROLE_ID VARCHAR(240) NOT NULL,
    SOURCE_ROLE_REVISION BIGINT NOT NULL CHECK (SOURCE_ROLE_REVISION > 0),
    THREAD_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_THREAD (ID),
    TURN_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_TURN (ID),
    INSTRUCTION_REVISION VARCHAR(160) NOT NULL,
    INSTRUCTION_DIGEST CHAR(64) NOT NULL,
    ADOPTED_ROLE_REVISION BIGINT,
    ADOPTED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (SOURCE_ROLE_ID, SOURCE_ROLE_REVISION)
        REFERENCES CORE.AGENT_ROLE (ID, REVISION),
    FOREIGN KEY (SOURCE_ROLE_ID, ADOPTED_ROLE_REVISION)
        REFERENCES CORE.AGENT_ROLE (ID, REVISION),
    CHECK ((ADOPTED_ROLE_REVISION IS NULL) = (ADOPTED_AT IS NULL)),
    CHECK (ADOPTED_ROLE_REVISION IS NULL OR ADOPTED_ROLE_REVISION > SOURCE_ROLE_REVISION)
);
CREATE INDEX CORE.PROMPT_OPTIMIZATION_BY_WORKSPACE ON CORE.PROMPT_OPTIMIZATION (WORKSPACE_ID, CREATED_AT DESC, ID);
CREATE TABLE CORE.EXECUTION_CONFIGURATION (
    SCOPE_KEY VARCHAR(120) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) REFERENCES CORE.WORKSPACE (ID),
    THREAD_ID CHAR(36) REFERENCES CORE.AGENT_THREAD (ID),
    PAYLOAD CLOB NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (THREAD_ID IS NULL OR WORKSPACE_ID IS NOT NULL)
);
CREATE TABLE CORE.AGENT_ROLE_IMPORT (
    ID CHAR(36) PRIMARY KEY,
    CONTENT_DIGEST CHAR(64) NOT NULL,
    PREVIEW_PAYLOAD CLOB NOT NULL,
    COMMITTED_ROLE_ID VARCHAR(240),
    COMMITTED_ROLE_REVISION BIGINT,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMMITTED_AT TIMESTAMP WITH TIME ZONE,
    CHECK ((COMMITTED_ROLE_ID IS NULL) = (COMMITTED_ROLE_REVISION IS NULL)),
    CHECK ((COMMITTED_ROLE_ID IS NULL) = (COMMITTED_AT IS NULL)),
    FOREIGN KEY (COMMITTED_ROLE_ID, COMMITTED_ROLE_REVISION) REFERENCES CORE.AGENT_ROLE (ID, REVISION)
);
CREATE TABLE CORE.EMBEDDING_BINDING (
    SINGLETON BOOLEAN PRIMARY KEY CHECK (SINGLETON = TRUE),
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL CHECK (PROVIDER_REVISION > 0),
    MODEL VARCHAR(1000) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (PROVIDER_ID, PROVIDER_REVISION) REFERENCES CORE.PROVIDER (ID, REVISION)
);
CREATE TABLE CORE.WORKTREE (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PARENT_THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    CHILD_THREAD_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_THREAD (ID),
    EXECUTION_ROOT VARCHAR(4096) NOT NULL UNIQUE,
    BASE_COMMIT VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    BACKUP_DIGEST CHAR(64) REFERENCES CORE.ATTACHMENT (DIGEST),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (PARENT_THREAD_ID <> CHILD_THREAD_ID)
);
CREATE INDEX CORE.WORKTREE_BY_WORKSPACE ON CORE.WORKTREE (WORKSPACE_ID, CREATED_AT, ID);
CREATE INDEX CORE.WORKTREE_BY_PARENT ON CORE.WORKTREE (PARENT_THREAD_ID, STATE, CREATED_AT);
CREATE TABLE CORE.PROVIDER_STATE (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    MODEL_ID VARCHAR(512) NOT NULL,
    PROVIDER_ID VARCHAR(240) NOT NULL,
    FORMAT VARCHAR(160) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    PAYLOAD_DIGEST CHAR(64) NOT NULL,
    THROUGH_SEQUENCE BIGINT NOT NULL CHECK (THROUGH_SEQUENCE > 0),
    ESTIMATED_INPUT_TOKENS BIGINT NOT NULL CHECK (ESTIMATED_INPUT_TOKENS >= 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX CORE.PROVIDER_STATE_BY_THREAD ON CORE.PROVIDER_STATE (THREAD_ID, MODEL_ID, THROUGH_SEQUENCE);
CREATE TABLE CORE.PERMISSION_PROFILE (
    ID VARCHAR(240) NOT NULL,
    VERSION BIGINT NOT NULL CHECK (VERSION > 0),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, VERSION)
);
