CREATE SCHEMA IF NOT EXISTS CORE;

CREATE TABLE CORE.WORKSPACE (
    ID CHAR(36) PRIMARY KEY,
    NAME VARCHAR(240) NOT NULL,
    ROOT_PATH VARCHAR(4096) NOT NULL UNIQUE,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.WORKSPACE_INSTRUCTION_SETTING (
    WORKSPACE_ID CHAR(36) PRIMARY KEY REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    FALLBACK_BASENAME VARCHAR(120),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.AGENT_THREAD (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PARENT_THREAD_ID CHAR(36) REFERENCES CORE.AGENT_THREAD (ID),
    EXECUTION_INTENT VARCHAR(32) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    NEXT_SEQUENCE BIGINT NOT NULL DEFAULT 1 CHECK (NEXT_SEQUENCE > 0),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.AGENT_TURN (
    ID CHAR(36) PRIMARY KEY,
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    STATUS VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    INPUT_TOKENS BIGINT NOT NULL CHECK (INPUT_TOKENS > 0),
    OUTPUT_TOKENS BIGINT NOT NULL CHECK (OUTPUT_TOKENS > 0),
    TOOL_CALLS INT NOT NULL CHECK (TOOL_CALLS > 0),
    CHILD_THREADS INT NOT NULL CHECK (CHILD_THREADS BETWEEN 0 AND 4),
    WALL_TIME_MILLIS BIGINT NOT NULL CHECK (WALL_TIME_MILLIS > 0),
    PROFILE_ID VARCHAR(240) NOT NULL,
    PROFILE_REVISION BIGINT NOT NULL CHECK (PROFILE_REVISION > 0),
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL CHECK (PROVIDER_REVISION > 0),
    MODEL VARCHAR(500) NOT NULL,
    PERMISSION_PROFILE_ID VARCHAR(240) NOT NULL,
    PERMISSION_PROFILE_VERSION BIGINT NOT NULL CHECK (PERMISSION_PROFILE_VERSION > 0),
    EXECUTION_ROOT VARCHAR(4096) NOT NULL,
    PROMPT_MANIFEST_DIGEST CHAR(64) NOT NULL,
    TOOL_CATALOG_DIGEST CHAR(64) NOT NULL,
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.TURN_CANCELLATION (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    REASON VARCHAR(500) NOT NULL,
    REQUESTED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.TURN_PROMPT_SNAPSHOT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PAYLOAD CLOB NOT NULL,
    DIGEST CHAR(64) NOT NULL
);

CREATE TABLE CORE.TURN_TOOL_CATALOG_SNAPSHOT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PAYLOAD CLOB NOT NULL,
    DIGEST CHAR(64) NOT NULL
);

CREATE TABLE CORE.TURN_UNATTENDED_EXECUTION_SCOPE (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    SCHEDULE_ID VARCHAR(240) NOT NULL,
    SCHEDULE_REVISION BIGINT NOT NULL CHECK (SCHEDULE_REVISION > 0),
    OCCURRENCE_ID VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.TURN_UNATTENDED_SCOPE_BY_OCCURRENCE
    ON CORE.TURN_UNATTENDED_EXECUTION_SCOPE (WORKSPACE_ID, SCHEDULE_ID, SCHEDULE_REVISION, OCCURRENCE_ID);

CREATE TABLE CORE.TURN_EXECUTION_CHECKPOINT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    PHASE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    INPUT_TOKENS BIGINT NOT NULL CHECK (INPUT_TOKENS >= 0),
    OUTPUT_TOKENS BIGINT NOT NULL CHECK (OUTPUT_TOKENS >= 0),
    REASONING_TOKENS BIGINT NOT NULL CHECK (REASONING_TOKENS >= 0),
    CACHED_INPUT_TOKENS BIGINT NOT NULL CHECK (CACHED_INPUT_TOKENS >= 0),
    CONSUMED_TOOL_CALLS INT NOT NULL CHECK (CONSUMED_TOOL_CALLS >= 0),
    MODEL_INVOCATIONS INT NOT NULL CHECK (MODEL_INVOCATIONS >= 0),
    TOOL_BATCH CLOB NOT NULL,
    NEXT_TOOL_INDEX INT NOT NULL CHECK (NEXT_TOOL_INDEX >= 0),
    VISIBLE_TOOLS CLOB NOT NULL,
    ACTIVE_INTENT_DIGEST CHAR(64),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((PHASE IN (
        'MODEL_IN_FLIGHT', 'TOOL_WAITING_APPROVAL', 'TOOL_APPROVAL_RESOLVED', 'TOOL_IN_FLIGHT'
    )) = (ACTIVE_INTENT_DIGEST IS NOT NULL))
);

CREATE TABLE CORE.APPROVAL_REQUEST (
    ID VARCHAR(160) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CALL_ID VARCHAR(240) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOOL_NAME VARCHAR(320) NOT NULL,
    TOOL_REVISION BIGINT NOT NULL CHECK (TOOL_REVISION > 0),
    RISK VARCHAR(32) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    EXPLANATION VARCHAR(1000) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    RESOLUTION_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (TURN_ID, CALL_ID)
);

CREATE INDEX CORE.APPROVAL_BY_STATE ON CORE.APPROVAL_REQUEST (STATE, CREATED_AT);

CREATE TABLE CORE.ITEM (
    ID CHAR(36) PRIMARY KEY,
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    SEQUENCE BIGINT NOT NULL CHECK (SEQUENCE > 0),
    KIND VARCHAR(160) NOT NULL,
    SCHEMA_ID VARCHAR(320) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    UNIQUE (THREAD_ID, SEQUENCE)
);

CREATE INDEX CORE.ITEM_BY_TURN ON CORE.ITEM (TURN_ID, SEQUENCE);

CREATE TABLE CORE.EVENT (
    SEQUENCE BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    THREAD_ID CHAR(36),
    TURN_ID CHAR(36),
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOPIC VARCHAR(320) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.OUTBOX (
    ID CHAR(36) PRIMARY KEY,
    DESTINATION VARCHAR(320) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(500) NOT NULL UNIQUE,
    PAYLOAD CLOB NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    ATTEMPTS INT NOT NULL DEFAULT 0 CHECK (ATTEMPTS >= 0),
    NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.COMMAND_RESULT (
    IDEMPOTENCY_KEY VARCHAR(200) PRIMARY KEY,
    METHOD_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    RESPONSE_PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.EFFECT_RECEIPT (
    IDEMPOTENCY_KEY VARCHAR(500) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CALL_ID VARCHAR(240) NOT NULL,
    PRODUCER_ID VARCHAR(240) NOT NULL,
    TOOL_NAME VARCHAR(320) NOT NULL,
    TOOL_REVISION BIGINT NOT NULL CHECK (TOOL_REVISION > 0),
    REQUEST_DIGEST CHAR(64) NOT NULL,
    RESULT_DIGEST CHAR(64) NOT NULL,
    RESULT_PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.ATTACHMENT (
    DIGEST CHAR(64) PRIMARY KEY,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    BLOB_PATH VARCHAR(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.ATTACHMENT_GLOBAL_CLAIM (
    ATTACHMENT_DIGEST CHAR(64) PRIMARY KEY REFERENCES CORE.ATTACHMENT (DIGEST) ON DELETE CASCADE,
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.ATTACHMENT_WORKSPACE_CLAIM (
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    ATTACHMENT_DIGEST CHAR(64) NOT NULL REFERENCES CORE.ATTACHMENT (DIGEST) ON DELETE CASCADE,
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (WORKSPACE_ID, ATTACHMENT_DIGEST)
);

CREATE TABLE CORE.ATTACHMENT_UPLOAD_QUOTA (
    ID SMALLINT PRIMARY KEY CHECK (ID = 1)
);

INSERT INTO CORE.ATTACHMENT_UPLOAD_QUOTA (ID) VALUES (1);

CREATE TABLE CORE.ATTACHMENT_UPLOAD (
    ID CHAR(36) PRIMARY KEY,
    SCOPE_KIND VARCHAR(24) NOT NULL CHECK (SCOPE_KIND IN ('GLOBAL', 'WORKSPACE')),
    WORKSPACE_ID CHAR(36) REFERENCES CORE.WORKSPACE (ID) ON DELETE CASCADE,
    STATE VARCHAR(24) NOT NULL CHECK (STATE IN ('ACTIVE', 'COMPLETED', 'ABORTED', 'FAILED', 'EXPIRED')),
    MEDIA_TYPE VARCHAR(240) NOT NULL,
    EXPECTED_DIGEST CHAR(64) NOT NULL,
    EXPECTED_BYTES BIGINT NOT NULL CHECK (EXPECTED_BYTES BETWEEN 1 AND 67108864),
    RECEIVED_BYTES BIGINT NOT NULL CHECK (RECEIVED_BYTES BETWEEN 0 AND EXPECTED_BYTES),
    NEXT_CHUNK_INDEX INTEGER NOT NULL CHECK (NEXT_CHUNK_INDEX BETWEEN 0 AND 1024),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    ATTACHMENT_DIGEST CHAR(64) REFERENCES CORE.ATTACHMENT (DIGEST),
    FAILURE_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((SCOPE_KIND = 'WORKSPACE') = (WORKSPACE_ID IS NOT NULL)),
    CHECK ((STATE = 'COMPLETED') = (ATTACHMENT_DIGEST IS NOT NULL)),
    CHECK ((STATE IN ('ABORTED', 'FAILED', 'EXPIRED')) = (FAILURE_REASON IS NOT NULL))
);

CREATE INDEX CORE.IDX_ATTACHMENT_UPLOAD_ACTIVE
    ON CORE.ATTACHMENT_UPLOAD (STATE, EXPIRES_AT);

CREATE TABLE CORE.PROFILE (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    LIFECYCLE VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);

CREATE TABLE CORE.PROVIDER (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    LIFECYCLE VARCHAR(32) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);

CREATE INDEX CORE.PROFILE_LATEST ON CORE.PROFILE (ID, REVISION DESC);
CREATE INDEX CORE.PROVIDER_LATEST ON CORE.PROVIDER (ID, REVISION DESC);

CREATE TABLE CORE.PROVIDER_VERIFICATION (
    IDEMPOTENCY_KEY VARCHAR(200) PRIMARY KEY,
    METHOD_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL CHECK (PROVIDER_REVISION > 0),
    MODEL VARCHAR(500) NOT NULL,
    STATE VARCHAR(32) NOT NULL
        CHECK (STATE IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'CANCELLED', 'UNKNOWN_OUTCOME')),
    RESULT_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK ((STATE = 'RUNNING') = (RESULT_PAYLOAD IS NULL)),
    FOREIGN KEY (PROVIDER_ID, PROVIDER_REVISION) REFERENCES CORE.PROVIDER (ID, REVISION)
);

CREATE TABLE CORE.PROMPT_OPTIMIZATION (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    SOURCE_PROFILE_ID VARCHAR(240) NOT NULL,
    SOURCE_PROFILE_REVISION BIGINT NOT NULL CHECK (SOURCE_PROFILE_REVISION > 0),
    THREAD_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_THREAD (ID),
    TURN_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_TURN (ID),
    INSTRUCTION_REVISION VARCHAR(160) NOT NULL,
    INSTRUCTION_DIGEST CHAR(64) NOT NULL,
    ADOPTED_PROFILE_REVISION BIGINT,
    ADOPTED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (SOURCE_PROFILE_ID, SOURCE_PROFILE_REVISION)
        REFERENCES CORE.PROFILE (ID, REVISION),
    FOREIGN KEY (SOURCE_PROFILE_ID, ADOPTED_PROFILE_REVISION)
        REFERENCES CORE.PROFILE (ID, REVISION),
    CHECK ((ADOPTED_PROFILE_REVISION IS NULL) = (ADOPTED_AT IS NULL)),
    CHECK (ADOPTED_PROFILE_REVISION IS NULL OR ADOPTED_PROFILE_REVISION > SOURCE_PROFILE_REVISION)
);

CREATE INDEX CORE.PROMPT_OPTIMIZATION_BY_WORKSPACE
    ON CORE.PROMPT_OPTIMIZATION (WORKSPACE_ID, CREATED_AT DESC, ID);

CREATE TABLE CORE.PROFILE_BINDING (
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    THREAD_ID CHAR(36) REFERENCES CORE.AGENT_THREAD (ID),
    SCOPE_KEY VARCHAR(80) NOT NULL,
    PROFILE_ID VARCHAR(240) NOT NULL,
    PROFILE_REVISION BIGINT NOT NULL CHECK (PROFILE_REVISION > 0),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (WORKSPACE_ID, SCOPE_KEY)
);

CREATE TABLE CORE.WORKTREE (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PARENT_THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    CHILD_THREAD_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_THREAD (ID),
    EXECUTION_ROOT VARCHAR(4096) NOT NULL UNIQUE,
    BASE_COMMIT VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    BACKUP_DIGEST CHAR(64) REFERENCES CORE.ATTACHMENT (DIGEST),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (PARENT_THREAD_ID <> CHILD_THREAD_ID)
);

CREATE INDEX CORE.WORKTREE_BY_WORKSPACE ON CORE.WORKTREE (WORKSPACE_ID, CREATED_AT, ID);
CREATE INDEX CORE.WORKTREE_BY_PARENT ON CORE.WORKTREE (PARENT_THREAD_ID, STATE, CREATED_AT);

CREATE TABLE CORE.PROVIDER_STATE (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    MODEL_ID VARCHAR(240) NOT NULL,
    PROVIDER_ID VARCHAR(240) NOT NULL,
    FORMAT VARCHAR(160) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    PAYLOAD_DIGEST CHAR(64) NOT NULL,
    THROUGH_SEQUENCE BIGINT NOT NULL CHECK (THROUGH_SEQUENCE > 0),
    ESTIMATED_INPUT_TOKENS BIGINT NOT NULL CHECK (ESTIMATED_INPUT_TOKENS >= 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.PROVIDER_STATE_BY_THREAD
    ON CORE.PROVIDER_STATE (THREAD_ID, MODEL_ID, THROUGH_SEQUENCE);

CREATE TABLE CORE.PERMISSION_PROFILE (
    ID VARCHAR(240) NOT NULL,
    VERSION BIGINT NOT NULL CHECK (VERSION > 0),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, VERSION)
);

CREATE TABLE CORE.EXTENSION (
    ID VARCHAR(240) PRIMARY KEY,
    TRUST_LEVEL VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE_REVISION BIGINT DEFAULT 1 NOT NULL CHECK (STATE_REVISION > 0),
    DESCRIPTOR CLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.EXTENSION_TRUST_KEY (
    KEY_ID VARCHAR(80) PRIMARY KEY,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    FINGERPRINT CHAR(64) NOT NULL UNIQUE,
    ATTACHMENT_DIGEST CHAR(64) NOT NULL REFERENCES CORE.ATTACHMENT (DIGEST),
    PUBLIC_KEY VARBINARY(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.THIRD_PARTY_BUNDLE (
    EXTENSION_ID VARCHAR(240) PRIMARY KEY REFERENCES CORE.EXTENSION (ID) ON DELETE CASCADE,
    MANIFEST_DIGEST CHAR(64) NOT NULL UNIQUE,
    SIGNING_KEY_ID VARCHAR(80) NOT NULL REFERENCES CORE.EXTENSION_TRUST_KEY (KEY_ID),
    INSTALL_DIRECTORY VARCHAR(160) NOT NULL UNIQUE,
    PERMISSION_REVIEW CLOB NOT NULL,
    FAILURE_COUNT INT NOT NULL DEFAULT 0 CHECK (FAILURE_COUNT >= 0),
    HEALTH_STATE VARCHAR(32) NOT NULL DEFAULT 'NOT_PROBED',
    LAST_HEALTH_AT TIMESTAMP WITH TIME ZONE,
    NEXT_RETRY_AT TIMESTAMP WITH TIME ZONE,
    LAST_FAILURE VARCHAR(1000),
    PENDING_TRASH_NAME VARCHAR(160)
);

CREATE TABLE CORE.THIRD_PARTY_REMOVAL (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    DESCRIPTOR CLOB NOT NULL,
    MANIFEST_DIGEST CHAR(64) NOT NULL,
    SIGNING_KEY_ID VARCHAR(80) NOT NULL REFERENCES CORE.EXTENSION_TRUST_KEY (KEY_ID),
    PERMISSION_REVIEW CLOB NOT NULL,
    TRASH_NAME VARCHAR(160) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REMOVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    RESTORED_REVISION BIGINT,
    PURGED_AT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (EXTENSION_ID, REVISION)
);

CREATE UNIQUE INDEX CORE.THIRD_PARTY_REMOVAL_BY_TRASH ON CORE.THIRD_PARTY_REMOVAL (TRASH_NAME);

CREATE TABLE CORE.EXTENSION_SCHEMA (
    EXTENSION_ID VARCHAR(240) PRIMARY KEY,
    SCHEMA_NAME VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE CORE.THIRD_PARTY_DOCUMENT (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    COLLECTION_NAME VARCHAR(240) NOT NULL,
    DOCUMENT_KEY VARCHAR(500) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (EXTENSION_ID, COLLECTION_NAME, DOCUMENT_KEY)
);

CREATE TABLE CORE.THIRD_PARTY_BLOB (
    EXTENSION_ID VARCHAR(240) NOT NULL,
    DIGEST CHAR(64) NOT NULL,
    BYTE_LENGTH BIGINT NOT NULL CHECK (BYTE_LENGTH >= 0),
    BLOB_PATH VARCHAR(4096) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (EXTENSION_ID, DIGEST)
);

CREATE TABLE CORE.LIFECYCLE_LEASE (
    ID CHAR(36) PRIMARY KEY,
    OWNER VARCHAR(240) NOT NULL,
    KIND VARCHAR(80) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.VAULT_KEY_STATE (
    SINGLETON BOOLEAN PRIMARY KEY CHECK (SINGLETON = TRUE),
    ACTIVE_KEY_ID VARCHAR(120) NOT NULL,
    PREVIOUS_KEY_ID VARCHAR(120),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (PREVIOUS_KEY_ID IS NULL OR PREVIOUS_KEY_ID <> ACTIVE_KEY_ID)
);

CREATE TABLE CORE.CREDENTIAL_SECRET (
    NAMESPACE VARCHAR(240) NOT NULL,
    SECRET_ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    FORMAT_VERSION INT NOT NULL CHECK (FORMAT_VERSION > 0),
    NONCE VARBINARY(12) NOT NULL,
    CIPHERTEXT BLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (NAMESPACE, SECRET_ID),
    CHECK (OCTET_LENGTH(NONCE) = 12),
    CHECK (OCTET_LENGTH(CIPHERTEXT) >= 16)
);

CREATE TABLE CORE.INPUT_REQUEST (
    ID VARCHAR(240) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    PRODUCER_ID VARCHAR(240) NOT NULL,
    PROMPT VARCHAR(1000) NOT NULL,
    RESPONSE_SCHEMA CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    RESPONSE_PAYLOAD CLOB,
    RESOLUTION_REASON VARCHAR(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (EXPIRES_AT > CREATED_AT),
    CHECK ((STATE = 'RESOLVED') = (RESPONSE_PAYLOAD IS NOT NULL)),
    CHECK ((STATE IN ('EXPIRED', 'CANCELLED')) = (RESOLUTION_REASON IS NOT NULL))
);

CREATE INDEX CORE.INPUT_REQUEST_BY_TURN ON CORE.INPUT_REQUEST (TURN_ID, CREATED_AT, ID);
CREATE INDEX CORE.INPUT_REQUEST_BY_STATE ON CORE.INPUT_REQUEST (STATE, EXPIRES_AT);

CREATE TABLE CORE.EXTENSION_JOB (
    ID VARCHAR(240) PRIMARY KEY,
    EXTENSION_ID VARCHAR(240) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    JOB_TYPE VARCHAR(240) NOT NULL,
    DEFINITION_ID VARCHAR(240) NOT NULL,
    DEFINITION_REVISION BIGINT NOT NULL CHECK (DEFINITION_REVISION > 0),
    FROZEN_INPUT CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    CHECKPOINT CLOB NOT NULL,
    NEXT_UNIT_SEQUENCE BIGINT NOT NULL CHECK (NEXT_UNIT_SEQUENCE > 0),
    ACTIVE_UNIT_SEQUENCE BIGINT,
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (ACTIVE_UNIT_SEQUENCE IS NULL OR (ACTIVE_UNIT_SEQUENCE > 0 AND ACTIVE_UNIT_SEQUENCE < NEXT_UNIT_SEQUENCE)),
    CHECK ((STATE = 'FAILED') = (ERROR_CODE IS NOT NULL)),
    CHECK (ACTIVE_UNIT_SEQUENCE IS NULL OR STATE = 'RUNNING')
);

CREATE INDEX CORE.EXTENSION_JOB_BY_WORKSPACE
    ON CORE.EXTENSION_JOB (WORKSPACE_ID, UPDATED_AT DESC, ID);
CREATE INDEX CORE.EXTENSION_JOB_RUNNABLE
    ON CORE.EXTENSION_JOB (STATE, UPDATED_AT, ID);

CREATE TABLE CORE.EXTENSION_JOB_UNIT (
    JOB_ID VARCHAR(240) NOT NULL REFERENCES CORE.EXTENSION_JOB (ID) ON DELETE CASCADE,
    UNIT_SEQUENCE BIGINT NOT NULL CHECK (UNIT_SEQUENCE > 0),
    UNIT_ID VARCHAR(240) NOT NULL,
    INTENT CLOB NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RESULT_PAYLOAD CLOB,
    CHECKPOINT CLOB,
    TURN_ID CHAR(36) REFERENCES CORE.AGENT_TURN (ID),
    EFFECT_RECEIPT_KEY VARCHAR(500),
    ERROR_CODE VARCHAR(160),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (JOB_ID, UNIT_SEQUENCE),
    UNIQUE (JOB_ID, UNIT_ID),
    CHECK ((STATE = 'INTENT_RECORDED') = (COMPLETED_AT IS NULL)),
    CHECK ((STATE = 'COMPLETED') = (CHECKPOINT IS NOT NULL)),
    CHECK ((STATE = 'FAILED') = (ERROR_CODE IS NOT NULL))
);

CREATE TABLE CORE.EXTENSION_JOB_INPUT_WAIT (
    JOB_ID VARCHAR(240) PRIMARY KEY REFERENCES CORE.EXTENSION_JOB (ID) ON DELETE CASCADE,
    REQUEST_ID VARCHAR(240) NOT NULL UNIQUE REFERENCES CORE.INPUT_REQUEST (ID) ON DELETE CASCADE,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.EXTENSION_JOB_INPUT_WAIT_BY_REQUEST
    ON CORE.EXTENSION_JOB_INPUT_WAIT (REQUEST_ID);

CREATE TABLE CORE.PRIVATE_NETWORK_GRANT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);

CREATE INDEX CORE.PRIVATE_NETWORK_GRANT_LATEST
    ON CORE.PRIVATE_NETWORK_GRANT (WORKSPACE_ID, ID, REVISION DESC);

CREATE TABLE CORE.UNATTENDED_TOOL_GRANT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);

CREATE INDEX CORE.UNATTENDED_TOOL_GRANT_LATEST
    ON CORE.UNATTENDED_TOOL_GRANT (WORKSPACE_ID, ID, REVISION DESC);

CREATE TABLE CORE.UNATTENDED_TOOL_USE (
    GRANT_ID VARCHAR(240) NOT NULL,
    INVOCATION_ID VARCHAR(240) NOT NULL,
    GRANT_REVISION BIGINT NOT NULL CHECK (GRANT_REVISION > 0),
    OUTCOME VARCHAR(32) NOT NULL,
    CONSUMED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (GRANT_ID, INVOCATION_ID),
    FOREIGN KEY (GRANT_ID, GRANT_REVISION)
        REFERENCES CORE.UNATTENDED_TOOL_GRANT (ID, REVISION)
);

CREATE INDEX CORE.UNATTENDED_TOOL_USE_BY_GRANT
    ON CORE.UNATTENDED_TOOL_USE (GRANT_ID, CONSUMED_AT);

CREATE TABLE CORE.PERMISSION_DECISION_TRACE (
    ID VARCHAR(240) PRIMARY KEY,
    DECISION_SEQUENCE BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    GRANT_KIND VARCHAR(32) NOT NULL,
    GRANT_ID VARCHAR(240) NOT NULL,
    ALLOWED BOOLEAN NOT NULL,
    PAYLOAD CLOB NOT NULL,
    DECIDED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.PERMISSION_DECISION_BY_GRANT
    ON CORE.PERMISSION_DECISION_TRACE (
        WORKSPACE_ID,
        GRANT_KIND,
        GRANT_ID,
        DECIDED_AT DESC,
        DECISION_SEQUENCE DESC
    );

CREATE TABLE CORE.MCP_ENDPOINT (
    ID VARCHAR(240) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION >= 0),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);

CREATE INDEX CORE.MCP_ENDPOINT_LATEST
    ON CORE.MCP_ENDPOINT (WORKSPACE_ID, ID, REVISION DESC);

CREATE TABLE CORE.MCP_CATALOG_ENTRY (
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION > 0),
    KIND VARCHAR(32) NOT NULL,
    ENTRY_NAME VARCHAR(160) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    PRIMARY KEY (ENDPOINT_ID, CATALOG_REVISION, KIND, ENTRY_NAME)
);

CREATE INDEX CORE.MCP_CATALOG_PAGE
    ON CORE.MCP_CATALOG_ENTRY (ENDPOINT_ID, CATALOG_REVISION, KIND, ENTRY_NAME);

CREATE TABLE CORE.MCP_CATALOG_REFRESH (
    ENDPOINT_ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    STATE VARCHAR(32) NOT NULL,
    PAGES_COMPLETED INT NOT NULL CHECK (PAGES_COMPLETED BETWEEN 0 AND 50),
    ENTRIES_DISCOVERED INT NOT NULL CHECK (ENTRIES_DISCOVERED BETWEEN 0 AND 10000),
    COMMITTED_CATALOG_REVISION BIGINT CHECK (COMMITTED_CATALOG_REVISION > 0),
    DETAIL VARCHAR(500),
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.MCP_TOOL_INVOCATION (
    IDEMPOTENCY_KEY VARCHAR(500) PRIMARY KEY,
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    CATALOG_REVISION BIGINT NOT NULL CHECK (CATALOG_REVISION > 0),
    TOOL_NAME VARCHAR(160) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RESULT_PAYLOAD CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.MCP_TOOL_INVOCATION_BY_ENDPOINT
    ON CORE.MCP_TOOL_INVOCATION (ENDPOINT_ID, UPDATED_AT DESC);

CREATE TABLE CORE.MCP_HEALTH (
    ENDPOINT_ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    CHECKED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CORE.MCP_OAUTH_SESSION (
    ID VARCHAR(240) PRIMARY KEY,
    ENDPOINT_ID VARCHAR(240) NOT NULL,
    ENDPOINT_REVISION BIGINT NOT NULL CHECK (ENDPOINT_REVISION > 0),
    AUTHORIZATION_URI VARCHAR(4096) NOT NULL,
    CREDENTIAL_NAMESPACE VARCHAR(240) NOT NULL,
    CREDENTIAL_ID VARCHAR(240) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    DETAIL VARCHAR(500),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX CORE.MCP_OAUTH_BY_ENDPOINT
    ON CORE.MCP_OAUTH_SESSION (ENDPOINT_ID, UPDATED_AT DESC);
