CREATE TABLE IF NOT EXISTS CORE.PROVIDER_MODEL_CONTEXT (
    PROVIDER_ID VARCHAR(240) NOT NULL,
    PROVIDER_REVISION BIGINT NOT NULL,
    MODEL VARCHAR(1000) NOT NULL,
    CONTEXT_WINDOW_TOKENS BIGINT CHECK (CONTEXT_WINDOW_TOKENS >= 4),
    MAXIMUM_OUTPUT_TOKENS BIGINT CHECK (MAXIMUM_OUTPUT_TOKENS > 0),
    PRIMARY KEY (PROVIDER_ID, PROVIDER_REVISION, MODEL),
    FOREIGN KEY (PROVIDER_ID, PROVIDER_REVISION) REFERENCES CORE.PROVIDER (ID, REVISION),
    CHECK (CONTEXT_WINDOW_TOKENS IS NULL OR MAXIMUM_OUTPUT_TOKENS IS NULL
        OR MAXIMUM_OUTPUT_TOKENS <= CONTEXT_WINDOW_TOKENS)
);
CREATE TABLE IF NOT EXISTS CORE.TURN_CONTEXT_STATE (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    POLICY_JSON CLOB NOT NULL,
    POLICY_DIGEST CHAR(64) NOT NULL,
    WINDOW_JSON CLOB,
    WINDOW_DIGEST CHAR(64),
    THROUGH_SEQUENCE BIGINT NOT NULL DEFAULT 0 CHECK (THROUGH_SEQUENCE >= 0),
    REVISION BIGINT NOT NULL DEFAULT 1 CHECK (REVISION > 0),
    CHECK ((WINDOW_JSON IS NULL) = (WINDOW_DIGEST IS NULL))
);
CREATE TABLE IF NOT EXISTS CORE.TURN_COMPACTION_CALL (
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID) ON DELETE CASCADE,
    ORDINAL INT NOT NULL CHECK (ORDINAL > 0),
    STATE VARCHAR(32) NOT NULL CHECK (STATE IN ('IN_FLIGHT', 'COMMITTED', 'ABANDONED')),
    INTENT_DIGEST CHAR(64) NOT NULL,
    NATIVE_CALL BOOLEAN NOT NULL,
    BEFORE_TOKENS BIGINT NOT NULL CHECK (BEFORE_TOKENS >= 0),
    SOURCE_SEQUENCE BIGINT NOT NULL CHECK (SOURCE_SEQUENCE >= 0),
    AFTER_TOKENS BIGINT CHECK (AFTER_TOKENS >= 0),
    USAGE_JSON CLOB,
    RESULT_DIGEST CHAR(64),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (TURN_ID, ORDINAL),
    CHECK ((STATE = 'COMMITTED') = (RESULT_DIGEST IS NOT NULL)),
    CHECK ((STATE = 'COMMITTED') = (USAGE_JSON IS NOT NULL))
);
