CREATE TABLE IF NOT EXISTS CORE.CODING_ENVIRONMENT (
    WORKSPACE_ID CHAR(36) PRIMARY KEY REFERENCES CORE.WORKSPACE (ID),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    SPEC_JSON CLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.TURN_CODING_ENVIRONMENT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    ENVIRONMENT_JSON CLOB NOT NULL,
    ENVIRONMENT_DIGEST CHAR(64) NOT NULL,
    SELECTION_JSON CLOB,
    SELECTION_DIGEST CHAR(64),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.CODING_OPERATION (
    ID VARCHAR(240) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    CALL_ID VARCHAR(240) NOT NULL,
    OPERATION_NAME VARCHAR(120) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    EXECUTION_ROOT VARCHAR(4096) NOT NULL,
    STATE VARCHAR(40) NOT NULL CHECK (STATE IN
        ('PREPARED', 'STARTED', 'FINISHED', 'JOURNALED', 'CONFLICTED', 'FAILED', 'UNKNOWN_OUTCOME')),
    REQUEST_JSON CLOB NOT NULL,
    PREPARATION_JSON CLOB,
    DEPENDENCY_EVIDENCE_JSON CLOB,
    OUTPUT_JSON CLOB,
    RESULT_JSON CLOB,
    SUCCESS BOOLEAN,
    FACTS_JSON CLOB,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (TURN_ID, CALL_ID)
);
CREATE INDEX IF NOT EXISTS IX_CODING_OPERATION_WORKSPACE ON CORE.CODING_OPERATION (WORKSPACE_ID, CREATED_AT);

CREATE TABLE IF NOT EXISTS CORE.CODING_TERMINAL (
    ID VARCHAR(240) PRIMARY KEY,
    OPERATION_ID VARCHAR(240) NOT NULL REFERENCES CORE.CODING_OPERATION (ID),
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    STATE VARCHAR(40) NOT NULL,
    COMMAND_JSON CLOB NOT NULL,
    EXIT_CODE INT,
    OUTPUT_BYTES BIGINT NOT NULL DEFAULT 0 CHECK (OUTPUT_BYTES >= 0),
    INPUT_SEQUENCE BIGINT NOT NULL DEFAULT 0 CHECK (INPUT_SEQUENCE >= 0),
    INPUT_DIGEST CHAR(64),
    INPUT_STATE VARCHAR(40),
    FINAL_FACT_RECORDED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS CORE.CODING_TERMINAL_OUTPUT (
    SESSION_ID VARCHAR(240) NOT NULL REFERENCES CORE.CODING_TERMINAL (ID),
    OFFSET_BYTES BIGINT NOT NULL,
    CONTENT_DIGEST CHAR(64) NOT NULL,
    CONTENT_LENGTH INT NOT NULL CHECK (CONTENT_LENGTH > 0),
    PRIMARY KEY (SESSION_ID, OFFSET_BYTES)
);

CREATE TABLE IF NOT EXISTS CORE.CODING_TOOLCHAIN (
    ARTIFACT_DIGEST CHAR(64) NOT NULL,
    TOOLCHAIN_KIND VARCHAR(40) NOT NULL,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    ARTIFACT_JSON CLOB NOT NULL,
    PRIMARY KEY (WORKSPACE_ID, TOOLCHAIN_KIND, ARTIFACT_DIGEST),
    INSTALLATION_ID VARCHAR(240) NOT NULL,
    JOB_ID VARCHAR(240),
    STATE VARCHAR(40) NOT NULL,
    ERROR_CODE VARCHAR(240),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.CODING_NETWORK_GRANT (
    ID VARCHAR(240) PRIMARY KEY,
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    OPERATION_ID VARCHAR(240) NOT NULL REFERENCES CORE.CODING_OPERATION (ID),
    GRANT_JSON CLOB NOT NULL,
    STATE VARCHAR(40) NOT NULL,
    TRANSFERRED_BYTES BIGINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.CODING_EXECUTION_ENVIRONMENT (
    SNAPSHOT_ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    SELECTION_JSON CLOB NOT NULL,
    SELECTION_DIGEST CHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.WORKSPACE_SECURITY_EVENT (
    ID CHAR(64) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    TURN_ID CHAR(36),
    EXECUTION_ROOT VARCHAR(8192) NOT NULL,
    CODE VARCHAR(120) NOT NULL,
    EVIDENCE_JSON CLOB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
