CREATE TABLE IF NOT EXISTS CORE.CODING_COMMAND_STREAM (
    OPERATION_ID VARCHAR(240) PRIMARY KEY REFERENCES CORE.CODING_OPERATION (ID),
    TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN (ID),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    MAXIMUM_BYTES BIGINT NOT NULL CHECK (MAXIMUM_BYTES BETWEEN 1 AND 1048576),
    OUTPUT_BYTES BIGINT NOT NULL DEFAULT 0 CHECK (OUTPUT_BYTES >= 0 AND OUTPUT_BYTES <= MAXIMUM_BYTES),
    STATE VARCHAR(40) NOT NULL DEFAULT 'RUNNING' CHECK (STATE IN ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT')),
    EXIT_CODE INT,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.CODING_COMMAND_CHUNK (
    OPERATION_ID VARCHAR(240) NOT NULL REFERENCES CORE.CODING_COMMAND_STREAM (OPERATION_ID),
    OFFSET_BYTES BIGINT NOT NULL CHECK (OFFSET_BYTES >= 0),
    CHANNEL VARCHAR(10) NOT NULL CHECK (CHANNEL IN ('stdout', 'stderr')),
    CONTENT_DIGEST CHAR(64) NOT NULL,
    CONTENT_LENGTH INT NOT NULL CHECK (CONTENT_LENGTH BETWEEN 1 AND 65536),
    PRIMARY KEY (OPERATION_ID, OFFSET_BYTES)
);
