CREATE TABLE IF NOT EXISTS CORE.CONVERSATION_COMPLETION_INIT (ID INT PRIMARY KEY);
INSERT INTO CORE.CONVERSATION_COMPLETION_INIT (ID)
    SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM CORE.CONVERSATION_COMPLETION_INIT WHERE ID = 1);
CREATE TABLE IF NOT EXISTS CORE.CONVERSATION_COMPLETION_HEAD (
    WORKSPACE_ID CHAR(36) PRIMARY KEY REFERENCES CORE.WORKSPACE (ID),
    COMMITTED_SEQUENCE BIGINT NOT NULL CHECK (COMMITTED_SEQUENCE >= 0)
);
CREATE TABLE IF NOT EXISTS CORE.CONVERSATION_EVIDENCE_EXCLUSION (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID)
);
CREATE TABLE IF NOT EXISTS CORE.CONVERSATION_COMPLETION (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD (ID),
    COMPLETION_SEQUENCE BIGINT NOT NULL CHECK (COMPLETION_SEQUENCE > 0),
    LAST_ITEM_SEQUENCE BIGINT NOT NULL CHECK (LAST_ITEM_SEQUENCE >= 0),
    COMPLETED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (WORKSPACE_ID, COMPLETION_SEQUENCE)
);
CREATE INDEX IF NOT EXISTS CORE.CONVERSATION_COMPLETION_PAGE
    ON CORE.CONVERSATION_COMPLETION (WORKSPACE_ID, COMPLETION_SEQUENCE, COMPLETED_AT);
