CREATE TABLE IF NOT EXISTS CORE.BROWSER_ORIGIN_PREVIEW (
    DIGEST CHAR(64) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE(ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD(ID),
    PAYLOAD CLOB NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSUMED BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS CORE.BROWSER_ORIGIN_GRANT (
    ID CHAR(36) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    STATE VARCHAR(32) NOT NULL CHECK (STATE IN ('ACTIVE', 'REVOKED')),
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE(ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD(ID),
    ORIGIN VARCHAR(1000) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CREATED_AT TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (ID, REVISION)
);
CREATE INDEX IF NOT EXISTS BROWSER_GRANT_THREAD ON CORE.BROWSER_ORIGIN_GRANT(THREAD_ID, CREATED_AT);
CREATE TABLE IF NOT EXISTS CORE.BROWSER_TURN_GRANT_SNAPSHOT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN(ID),
    SNAPSHOT_ID CHAR(36) NOT NULL UNIQUE,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE(ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD(ID),
    PAYLOAD CLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS CORE.BROWSER_GRANT_DECISION (
    ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE(ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD(ID),
    PAYLOAD CLOB NOT NULL,
    DECIDED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS BROWSER_DECISION_THREAD ON CORE.BROWSER_GRANT_DECISION(THREAD_ID, DECIDED_AT);
