CREATE TABLE IF NOT EXISTS CORE.TURN_CONTINUATION (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN(ID),
    PREVIOUS_TURN_ID CHAR(36) NOT NULL UNIQUE REFERENCES CORE.AGENT_TURN(ID),
    ORIGINAL_INPUT_TURN_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_TURN(ID),
    THREAD_ID CHAR(36) NOT NULL REFERENCES CORE.AGENT_THREAD(ID),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (TURN_ID <> PREVIOUS_TURN_ID),
    CHECK (TURN_ID <> ORIGINAL_INPUT_TURN_ID)
);
CREATE INDEX IF NOT EXISTS TURN_CONTINUATION_INPUT ON CORE.TURN_CONTINUATION(ORIGINAL_INPUT_TURN_ID);
