CREATE TABLE IF NOT EXISTS CORE.CODING_SYSTEM_REGISTRY (
    WORKSPACE_ID CHAR(36) PRIMARY KEY REFERENCES CORE.WORKSPACE (ID),
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    REGISTRY_JSON CLOB NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.TURN_SYSTEM_ENVIRONMENT (
    TURN_ID CHAR(36) PRIMARY KEY REFERENCES CORE.AGENT_TURN (ID),
    CATALOG_JSON CLOB NOT NULL,
    CATALOG_DIGEST CHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.CODING_EXECUTION_SYSTEM_ENVIRONMENT (
    SNAPSHOT_ID CHAR(36) PRIMARY KEY,
    WORKSPACE_ID CHAR(36) NOT NULL REFERENCES CORE.WORKSPACE (ID),
    CATALOG_JSON CLOB NOT NULL,
    CATALOG_DIGEST CHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
