CREATE SCHEMA IF NOT EXISTS ${schema};

CREATE TABLE IF NOT EXISTS ${schema}.SCHEMA_HISTORY (
    VERSION INT PRIMARY KEY,
    DESCRIPTION VARCHAR(240) NOT NULL,
    CHECKSUM CHAR(64) NOT NULL,
    INSTALLED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ${schema}.DOCUMENT (
    COLLECTION_NAME VARCHAR(240) NOT NULL,
    DOCUMENT_KEY VARCHAR(500) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    TOMBSTONED BOOLEAN NOT NULL DEFAULT FALSE,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (COLLECTION_NAME, DOCUMENT_KEY)
);

CREATE TABLE IF NOT EXISTS ${schema}.DOCUMENT_HISTORY (
    COLLECTION_NAME VARCHAR(240) NOT NULL,
    DOCUMENT_KEY VARCHAR(500) NOT NULL,
    REVISION BIGINT NOT NULL CHECK (REVISION > 0),
    PAYLOAD CLOB NOT NULL,
    TOMBSTONED BOOLEAN NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (COLLECTION_NAME, DOCUMENT_KEY, REVISION)
);

CREATE TABLE IF NOT EXISTS ${schema}.COMMAND_RESULT (
    IDEMPOTENCY_KEY VARCHAR(200) PRIMARY KEY,
    OPERATION VARCHAR(240) NOT NULL,
    REQUEST_DIGEST CHAR(64) NOT NULL,
    RESPONSE_PAYLOAD CLOB NOT NULL,
    RESPONSE_REVISION BIGINT NOT NULL CHECK (RESPONSE_REVISION >= 0),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
